### PR TITLE
OffflineData: adjust to API changes for upcoming deal.II 9.6.0

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Review by drwells — APPROVED** [review]

**Comment by tamiko** [comment]
We will need to wait a bit for the regression infrastructure to catch up with the development repo :laughing:

**Comment by drwells** [comment]
I know, I know...

The orientation status is such a mess. We have to make breaking changes because having 4+ different encodings is too much to manage.

**Comment by tamiko** [comment]
@drwells Thanks a lot for taking care of this! The disruption is really minor.

**Comment by drwells** [comment]
You're welcome. I am pretty sure that this is the last public-facing change, though there are many more internal things to clean up (like QProjector).

**Pull request merged**
